version: "3"

services:
  api:
    image: rudolfoborges/docker-sample-api
    ports:
      - 8081:8081
    deploy:
      replicas: 3
      update_config:
        parallelism: 2

  visualizer:
      image: dockersamples/visualizer:stable
      ports:
        - "8083:8080"
      stop_grace_period: 1m30s
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      deploy:
        placement:
          constraints: [node.role == manager]