version: "3"

services:
  api:
    image: rudolfoborges/docker-sample-api
    ports:
      - "8081:8081"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 60s

  web:
      image: rudolfoborges/docker-sample-web
      ports:
        - "8082:8082"
      deploy:
        replicas: 2
        update_config:
          parallelism: 1
          delay: 60s

  visualizer:
      image: dockersamples/visualizer:stable
      ports:
        - "8083:8080"
      stop_grace_period: 1m30s
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      deploy:
        placement:
          constraints: [node.role == manager]